name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]  # Запускать при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Даёт доступ к GitHub Pages
      id-token: write   # Позволяет Actions авторизоваться

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'  # Указываем папку site как источник

  deploy-to-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
